const DOMAINS = [
  { id: 'nature', name: 'Fundamentos de naturaleza', short: 'Naturaleza', color: '#4de4ff', description: 'Genes, especies, funciones ecológicas y sensibilidad' },
  { id: 'ecosystems', name: 'Ecosistemas y dependencias', short: 'Ecosistemas', color: '#62f2bd', description: 'Funciones, servicios, conectividad y resiliencia' },
  { id: 'mitigation', name: 'Mitigación y restauración', short: 'Mitigación', color: '#ffca67', description: 'Prevención, minimización, restauración y acción adaptativa' },
  { id: 'evidence', name: 'Medición y evidencia', short: 'Evidencia', color: '#ba9cff', description: 'Indicadores, líneas base, afirmaciones y calidad de decisión' },
  { id: 'airbus', name: 'Decisiones aplicadas en Airbus', short: 'Airbus', color: '#ff7f91', description: 'A400M, Eurofighter, instalaciones, compras y operaciones' },
];

const QUESTIONS = [
  {
    id: 1, domain: 'nature', difficulty: 'Fundamentos',
    question: '¿Qué tres niveles suelen considerarse al describir la diversidad de la naturaleza?',
    options: ['Clima, agua y suelo', 'Genes, especies y ecosistemas', 'Solo plantas, animales y hongos', 'Local, regional y global'], correct: 1,
    explanation: 'La naturaleza presenta diversidad dentro de las especies mediante la variación genética, entre especies diferentes y entre ecosistemas. Estos niveles interactúan: una menor variación genética puede debilitar a una especie, mientras que la degradación del hábitat puede afectar a muchas especies a la vez.',
    takeaway: 'No reduzcas la naturaleza a un simple recuento de especies: importan el estado y la diversidad de los tres niveles.',
  },
  {
    id: 2, domain: 'nature', difficulty: 'Fundamentos',
    question: '¿Qué hace que una especie endémica sea especialmente importante en una evaluación local?',
    options: ['Solo vive de noche', 'Su distribución natural está limitada a una zona concreta', 'Ha sido introducida por las personas', 'Es abundante en todo el mundo'], correct: 1,
    explanation: 'Una especie endémica aparece de forma natural en un área geográfica restringida. Por ello, un impacto local puede afectar a una proporción elevada de toda su población o hábitat, aumentando la importancia de la decisión.',
    takeaway: 'La distribución y el carácter irremplazable son tan importantes como el número de individuos observados.',
  },
  {
    id: 3, domain: 'nature', difficulty: 'Fundamentos',
    question: '¿Por qué la diversidad genética puede hacer que una población sea más resiliente?',
    options: ['Elimina toda competencia', 'Algunos individuos pueden tolerar mejor los cambios', 'Evita todas las enfermedades', 'Hace que todas las poblaciones sean idénticas'], correct: 1,
    explanation: 'La variación genética genera un abanico más amplio de características dentro de una población. Cuando cambian las enfermedades, la temperatura o las condiciones del hábitat, aumenta la probabilidad de que algunos individuos sobrevivan y se reproduzcan.',
    takeaway: 'Una población puede parecer numerosa y seguir siendo vulnerable si su diversidad genética es muy baja.',
  },
  {
    id: 4, domain: 'nature', difficulty: 'Aplicada',
    question: '¿Cuál es la diferencia principal entre una especie exótica y una especie invasora?',
    options: ['No existe ninguna diferencia', 'La invasora causa daños al establecerse y propagarse', 'La exótica siempre es venenosa', 'La invasora solo aparece en ciudades'], correct: 1,
    explanation: 'Una especie exótica ha sido trasladada fuera de su área natural, pero no es automáticamente invasora. Se convierte en invasora cuando su establecimiento y expansión generan daños ecológicos, económicos o sociales.',
    takeaway: 'La gestión debe basarse en evidencias de riesgo e impacto, no únicamente en que la especie resulte desconocida.',
  },
  {
    id: 5, domain: 'nature', difficulty: 'Aplicada',
    question: '¿Por qué la pérdida de una especie clave puede tener consecuencias desproporcionadas?',
    options: ['Todas las especies son intercambiables', 'Puede provocar cambios en cascada dentro de la red trófica', 'Solo cambia el aspecto del paisaje', 'Siempre aumenta la estabilidad del ecosistema'], correct: 1,
    explanation: 'Una especie clave ejerce una influencia ecológica elevada en relación con su abundancia. Su desaparición puede modificar presas, depredadores, vegetación o estructura del hábitat y producir efectos en todo el sistema.',
    takeaway: 'La importancia ecológica no puede deducirse únicamente de la abundancia.',
  },
  {
    id: 6, domain: 'nature', difficulty: 'Aplicada',
    question: '¿Qué es un bioindicador?',
    options: ['Un registro financiero obligatorio', 'Un organismo o comunidad que aporta información sobre el estado ambiental', 'Cualquier especie utilizada en una campaña', 'Un sensor que solo mide temperatura'], correct: 1,
    explanation: 'Los bioindicadores responden a las condiciones ambientales de una forma que puede revelar contaminación, calidad del hábitat o cambios ecológicos. Su interpretación requiere un método adecuado, una condición de referencia y conocimiento de otros factores influyentes.',
    takeaway: 'Un bioindicador solo es útil cuando se comprenden su respuesta ecológica y el método de medición.',
  },
  {
    id: 7, domain: 'nature', difficulty: 'Fundamentos',
    question: '¿Qué función ecológica realizan muchos insectos, aves y murciélagos?',
    options: ['Sellar el suelo', 'Polinizar las plantas', 'Aumentar la luz artificial', 'Eliminar las redes tróficas'], correct: 1,
    explanation: 'Muchas plantas con flor dependen de animales que transportan el polen y permiten su reproducción. La polinización sustenta la vegetación silvestre, los cultivos y las redes alimentarias y hábitats asociados.',
    takeaway: 'Proteger a los polinizadores también significa conservar lugares de nidificación, alimento y continuidad estacional.',
  },
  {
    id: 8, domain: 'nature', difficulty: 'Aplicada',
    question: '¿Por qué la luz artificial nocturna puede afectar a la fauna aunque no se observen animales heridos?',
    options: ['Mejora todos los hábitats', 'Puede alterar orientación, actividad y ciclos biológicos', 'Siempre reduce el ruido', 'Aumenta la diversidad genética'], correct: 1,
    explanation: 'La iluminación puede modificar el movimiento, la alimentación, la migración, la reproducción y las relaciones entre depredadores y presas. Los efectos pueden extenderse más allá de la superficie iluminada debido al resplandor y la luz reflejada.',
    takeaway: 'Primero cuestiona si la iluminación es necesaria; después controla duración, intensidad, dirección y espectro.',
  },
  {
    id: 9, domain: 'nature', difficulty: 'Avanzada',
    question: '¿Por qué analizar la red trófica es más sólido que evaluar cada especie de manera aislada?',
    options: ['Supone que todas las especies responden igual', 'Considera las relaciones ecológicas y los efectos indirectos', 'Elimina la necesidad de datos de campo', 'Se centra únicamente en los depredadores'], correct: 1,
    explanation: 'Las especies están conectadas mediante alimentación, competencia, polinización, descomposición y relaciones de hábitat. Una presión sobre un grupo puede afectar a otros aunque no estén expuestos directamente.',
    takeaway: 'La evaluación debe considerar funciones e interacciones, no solo una lista de especies presentes.',
  },
  {
    id: 10, domain: 'nature', difficulty: 'Aplicada',
    question: 'Antes de iniciar trabajos durante una época sensible de reproducción, ¿qué acción aporta la mejor base preventiva?',
    options: ['Empezar los trabajos y observar después', 'Realizar primero una prospección ecológica competente', 'Aumentar la iluminación', 'Retirar la vegetación inmediatamente'], correct: 1,
    explanation: 'Una prospección previa y proporcionada puede identificar nidos, refugios, rutas de movimiento o receptores sensibles. Los resultados permiten adaptar el diseño, la secuencia, el calendario y las zonas de exclusión antes de provocar molestias.',
    takeaway: 'La información ecológica temprana crea más opciones de prevención y reduce cambios urgentes posteriores.',
  },

  {
    id: 11, domain: 'ecosystems', difficulty: 'Fundamentos',
    question: '¿Qué son los servicios ecosistémicos?',
    options: ['Servicios comerciales de jardinería', 'Contribuciones de los ecosistemas a las personas y a la actividad económica', 'Únicamente productos agrícolas', 'Beneficios exclusivos de espacios protegidos'], correct: 1,
    explanation: 'Los ecosistemas contribuyen mediante provisión de materiales, regulación de procesos y valores no materiales. Estas contribuciones dependen de funciones ecológicas subyacentes como el ciclo de nutrientes, la formación del suelo y la provisión de hábitat.',
    takeaway: 'Una organización puede depender de la naturaleza aunque la dependencia sea indirecta o esté en su cadena de valor.',
  },
  {
    id: 12, domain: 'ecosystems', difficulty: 'Fundamentos',
    question: '¿Qué servicio puede proporcionar un humedal en buen estado?',
    options: ['Aumentar la erosión', 'Almacenar agua, filtrar contaminantes y aportar hábitat', 'Evitar todas las sequías', 'Eliminar cualquier variación estacional'], correct: 1,
    explanation: 'Los humedales pueden ralentizar el agua, retener sedimentos y nutrientes, albergar especies e influir en la hidrología local. Su funcionamiento depende del estado, la escala, la conectividad y la intensidad de las presiones.',
    takeaway: 'Un humedal reduce determinados riesgos; no debe presentarse como capaz de eliminar cualquier riesgo de inundación o calidad del agua.',
  },
  {
    id: 13, domain: 'ecosystems', difficulty: 'Fundamentos',
    question: '¿Qué describe la conectividad ecológica?',
    options: ['La cobertura digital en zonas rurales', 'La capacidad de organismos y procesos ecológicos para desplazarse entre hábitats', 'Una carretera que une dos edificios', 'Mantener a la fauna dentro de un recinto'], correct: 1,
    explanation: 'La conectividad permite dispersión, migración, intercambio genético y acceso a recursos. Depende de la calidad y disposición de los hábitats, las barreras, los puntos de apoyo y las necesidades de movimiento de cada especie.',
    takeaway: 'Un corredor dibujado en un mapa no es automáticamente funcional: deben evaluarse su uso y estado.',
  },
  {
    id: 14, domain: 'ecosystems', difficulty: 'Fundamentos',
    question: '¿Por qué debe considerarse el suelo un sistema vivo y no una superficie inerte?',
    options: ['No contiene organismos', 'Regula agua, nutrientes y carbono y alberga comunidades biológicas', 'Solo es relevante para la agricultura', 'Siempre se recupera inmediatamente después del sellado'], correct: 1,
    explanation: 'El suelo contiene comunidades biológicas complejas y aporta infiltración, ciclo de nutrientes, almacenamiento de carbono y soporte físico. La compactación, contaminación, erosión y sellado pueden reducir estas funciones durante largos periodos.',
    takeaway: 'Protege el estado y las funciones del suelo, no solo su superficie visible.',
  },
  {
    id: 15, domain: 'ecosystems', difficulty: 'Aplicada',
    question: '¿Cuál es una consecuencia habitual de la fragmentación del hábitat?',
    options: ['Mejora del movimiento para todas las especies', 'Aislamiento de poblaciones y aumento de los efectos de borde', 'Creación automática de hábitat nuevo', 'Ausencia de cambios fuera del límite del proyecto'], correct: 1,
    explanation: 'La fragmentación divide hábitats continuos en parches más pequeños. Puede dificultar el movimiento, reducir el intercambio genético y exponer una mayor proporción del hábitat a luz, ruido, depredadores o especies invasoras.',
    takeaway: 'La forma, conexión y usos circundantes pueden ser tan importantes como la superficie total del hábitat.',
  },
  {
    id: 16, domain: 'ecosystems', difficulty: 'Aplicada',
    question: '¿Para qué sirve una línea base ecológica?',
    options: ['Para justificar una decisión ya tomada', 'Para definir el estado inicial frente al que se evaluarán los cambios', 'Para sustituir el seguimiento futuro', 'Para registrar únicamente el gasto'], correct: 1,
    explanation: 'La línea base describe los receptores y condiciones relevantes antes de una intervención, indicando métodos, límites y momento de medición. Permite comparar observaciones posteriores y diferenciar los efectos del proyecto de la variación natural.',
    takeaway: 'Sin una línea base creíble resulta difícil verificar afirmaciones de mejora o deterioro.',
  },
  {
    id: 17, domain: 'ecosystems', difficulty: 'Avanzada',
    question: '¿Por qué debe evaluarse una instalación industrial a escala de paisaje o cuenca?',
    options: ['La instalación está aislada ecológicamente', 'El agua, las especies y las presiones atraviesan límites administrativos', 'Solo son válidos los datos nacionales', 'Los actores locales son irrelevantes'], correct: 1,
    explanation: 'Las especies se desplazan más allá de las vallas, el drenaje conecta distintos lugares y los proveedores o usos vecinos pueden afectar a los mismos receptores. Una escala mayor revela efectos acumulativos, dependencias y oportunidades que se pierden al mirar solo la parcela.',
    takeaway: 'Define los límites según los procesos ecológicos, no únicamente según la propiedad.',
  },
  {
    id: 18, domain: 'ecosystems', difficulty: 'Aplicada',
    question: '¿Qué es una dependencia de la naturaleza?',
    options: ['Un cambio provocado por una actividad', 'Una contribución ecosistémica de la que depende una actividad', 'Cualquier requisito legal ambiental', 'Un objetivo de comunicación'], correct: 1,
    explanation: 'Las dependencias incluyen disponibilidad fiable de agua, estabilidad del terreno, regulación climática, materiales y protección frente a peligros. Pueden generar riesgos operativos o de suministro cuando se deteriora el ecosistema que las sostiene.',
    takeaway: 'Los impactos describen lo que cambia la organización; las dependencias describen lo que necesita.',
  },
  {
    id: 19, domain: 'ecosystems', difficulty: 'Aplicada',
    question: '¿Qué distingue a una solución basada en la naturaleza creíble?',
    options: ['Utiliza imágenes de naturaleza', 'Responde a un reto real y aporta beneficios ecológicos verificables', 'Siempre consiste en plantar árboles', 'Sustituye cualquier solución técnica'], correct: 1,
    explanation: 'Una solución creíble se diseña para el contexto ecológico y social local, responde a un reto definido y evita daños o desplazamientos. Incluye resultados medibles, gobernanza y gestión a largo plazo.',
    takeaway: 'Evalúa la función, el contexto y la evidencia, no si la intervención simplemente parece natural.',
  },
  {
    id: 20, domain: 'ecosystems', difficulty: 'Avanzada',
    question: '¿Cuál es la diferencia entre resistencia y recuperación de un ecosistema?',
    options: ['No existe diferencia', 'La resistencia limita el cambio durante la perturbación y la recuperación se refiere al retorno posterior', 'La recuperación ocurre antes de la perturbación', 'La resistencia significa que el ecosistema nunca cambia'], correct: 1,
    explanation: 'La resistencia es la capacidad de soportar una presión sin experimentar grandes cambios. La recuperación es la capacidad de recuperar estructura o función después; la resiliencia puede incluir ambas, pero ningún ecosistema soporta perturbaciones ilimitadas.',
    takeaway: 'El seguimiento debe analizar tanto la respuesta inmediata como la trayectoria una vez finalizada la presión.',
  },

  {
    id: 21, domain: 'mitigation', difficulty: 'Fundamentos',
    question: '¿Cuál es el orden correcto de la jerarquía de mitigación?',
    options: ['Compensar, restaurar, minimizar y evitar', 'Evitar, minimizar, restaurar y solo después compensar los impactos residuales', 'Restaurar, evitar, compensar y minimizar', 'Medir, comunicar, compensar y cerrar'], correct: 1,
    explanation: 'La prevención impide que el impacto llegue a producirse. Los impactos restantes se minimizan, las zonas afectadas se restauran y la compensación solo se considera para impactos residuales después de aplicar los pasos anteriores.',
    takeaway: 'No utilices una futura restauración o compensación para eludir una opción viable de prevención.',
  },
  {
    id: 22, domain: 'mitigation', difficulty: 'Aplicada',
    question: '¿Qué actuación aplica mejor el principio de prevención de la jerarquía?',
    options: ['Reubicar los trabajos fuera de un hábitat sensible', 'Plantar vegetación después de construir', 'Publicar una campaña', 'Medir el daño al final'], correct: 0,
    explanation: 'Modificar la ubicación, el diseño, la tecnología o el calendario antes de que se produzca el impacto puede eliminar completamente la interacción. La prevención suele aportar mayor certeza que intentar reparar posteriormente el daño ecológico.',
    takeaway: 'Las decisiones tempranas de diseño crean las mejores oportunidades para evitar impactos.',
  },
  {
    id: 23, domain: 'mitigation', difficulty: 'Aplicada',
    question: 'Si la iluminación de seguridad imprescindible puede afectar a la fauna nocturna, ¿qué respuesta representa mejor la minimización?',
    options: ['Eliminar toda iluminación aunque afecte a la seguridad', 'Limitar duración, intensidad, orientación y dispersión manteniendo la función de seguridad', 'Añadir más iluminación sin evaluar', 'Suponer que el efecto es insignificante'], correct: 1,
    explanation: 'Cuando la actividad no puede evitarse, la minimización reduce la magnitud, duración o extensión de la exposición. El diseño debe responder tanto a la función de seguridad como a la sensibilidad de los receptores identificados.',
    takeaway: 'Una buena medida actúa sobre la vía de impacto y mantiene el requisito operativo legítimo.',
  },
  {
    id: 24, domain: 'mitigation', difficulty: 'Aplicada',
    question: '¿Qué necesita un plan sólido de restauración ecológica?',
    options: ['Solo una lista de especies', 'Una referencia, objetivos, actuaciones, indicadores, umbrales y mantenimiento', 'Una fotografía del primer día', 'Una promesa sin plazo'], correct: 1,
    explanation: 'La restauración pretende situar al ecosistema en una trayectoria de recuperación creíble. Necesita una referencia, resultados medibles, un método de ejecución, recursos, seguimiento y respuestas si el progreso es insuficiente.',
    takeaway: 'La restauración es un proceso gestionado en el tiempo, no una actividad de plantación de un solo día.',
  },
  {
    id: 25, domain: 'mitigation', difficulty: 'Avanzada',
    question: '¿Por qué la compensación ecológica no equivale a evitar el impacto?',
    options: ['La compensación siempre funciona inmediatamente', 'Algunos valores son irremplazables y la compensación implica incertidumbre y retrasos', 'La prevención solo es una acción de comunicación', 'La compensación no necesita seguimiento'], correct: 1,
    explanation: 'Un hábitat recreado puede diferir en estado, ubicación, función y madurez del que se pierde. Algunos impactos no pueden compensarse con confianza, especialmente cuando los receptores son críticos, únicos o tardan mucho en recuperarse.',
    takeaway: 'La compensación es el último paso para el impacto residual, no un permiso para ignorar los límites ecológicos.',
  },
  {
    id: 26, domain: 'mitigation', difficulty: 'Avanzada',
    question: '¿Qué significa adicionalidad en una medida de restauración o compensación?',
    options: ['La mejora se produciría de todas formas', 'La intervención genera un resultado superior a las obligaciones y a la línea base prevista', 'El proyecto tiene más presupuesto', 'El resultado no necesita evidencias'], correct: 1,
    explanation: 'Un resultado adicional no se produciría sin la intervención. Demostrarlo exige una línea base creíble, claridad sobre las obligaciones legales existentes y evidencias de que la mejora reclamada no es simplemente la evolución habitual.',
    takeaway: 'Contabiliza únicamente los resultados que la intervención añade realmente.',
  },
  {
    id: 27, domain: 'mitigation', difficulty: 'Aplicada',
    question: '¿Qué enfoque es más adecuado cuando se detecta en la instalación una especie potencialmente invasora?',
    options: ['Ignorarla', 'Retirarla inmediatamente sin identificarla ni definir un método', 'Confirmar la identificación, evaluar el riesgo y aplicar una respuesta controlada', 'Favorecer su expansión'], correct: 2,
    explanation: 'Una respuesta eficaz depende de la identificación correcta, la distribución, la vía de entrada y el riesgo ecológico. Una retirada mal planificada puede dispersar propágulos, dañar el hábitat nativo o provocar reinvasiones repetidas.',
    takeaway: 'Controla la vía de entrada y realiza seguimiento, no te limites a los individuos visibles.',
  },
  {
    id: 28, domain: 'mitigation', difficulty: 'Aplicada',
    question: '¿Qué es la gestión adaptativa?',
    options: ['Mantener el plan aunque fracase', 'Ajustar las actuaciones utilizando los resultados y desencadenantes previamente definidos', 'Cambiar los objetivos sin evidencias', 'Actuar sin indicadores'], correct: 1,
    explanation: 'La gestión adaptativa trata la ejecución como un proceso estructurado de aprendizaje. Se definen objetivos, indicadores, umbrales y medidas correctoras para que las evidencias mejoren las decisiones sin perder responsabilidad.',
    takeaway: 'Decide de antemano qué resultado activará un cambio en la medida.',
  },
  {
    id: 29, domain: 'mitigation', difficulty: 'Aplicada',
    question: '¿Qué principio de plantación es más sólido para restaurar un hábitat?',
    options: ['Elegir especies solo por su rápido crecimiento', 'Utilizar especies nativas diversas y adecuadas al lugar y al objetivo ecológico', 'Usar cualquier mezcla ornamental', 'Maximizar el número plantado sin considerar la supervivencia'], correct: 1,
    explanation: 'La selección debe considerar el hábitat de referencia, el suelo, el clima, la procedencia, las interacciones y la gestión a largo plazo. Una cifra elevada de plantación significa poco si las especies son inadecuadas o no consiguen establecerse.',
    takeaway: 'Mide establecimiento y función ecológica, no solo la actividad de plantación.',
  },
  {
    id: 30, domain: 'mitigation', difficulty: 'Avanzada',
    question: '¿Cómo mejora el pensamiento de ciclo de vida las decisiones de mitigación?',
    options: ['Analiza únicamente la instalación operativa', 'Ayuda a evitar el traslado de impactos entre etapas, lugares o materiales', 'Garantiza que una opción carezca de impactos', 'Sustituye el criterio de ingeniería'], correct: 1,
    explanation: 'Un cambio que reduce una presión local puede aumentar los impactos de extracción, transporte, mantenimiento o fin de vida en otro lugar. Unos límites de ciclo de vida coherentes hacen visibles los compromisos y apoyan mejores decisiones de diseño.',
    takeaway: 'Comprueba si una mejora aparente reduce realmente el impacto o solo traslada la carga.',
  },

  {
    id: 31, domain: 'evidence', difficulty: 'Fundamentos',
    question: '¿Cuál de estos es un indicador de estado y no de presión o respuesta?',
    options: ['Superficie de hábitat eliminada', 'Estado ecológico de un humedal', 'Número de medidas de restauración ejecutadas', 'Presupuesto asignado'], correct: 1,
    explanation: 'Los indicadores de estado describen la condición de la naturaleza. La superficie eliminada es una presión, mientras que las acciones y el presupuesto son respuestas o recursos; una cadena completa de evidencia conecta presión, actuación y resultado ecológico.',
    takeaway: 'No presentes un indicador de actividad como prueba de que la naturaleza ha mejorado.',
  },
  {
    id: 32, domain: 'evidence', difficulty: 'Fundamentos',
    question: '¿Qué hace que un indicador ambiental sea útil para tomar decisiones?',
    options: ['Es fácil de colocar en una diapositiva', 'Es relevante, está definido, puede medirse y compararse y se vincula a una decisión', 'Siempre aumenta', 'No tiene una unidad definida'], correct: 1,
    explanation: 'Un indicador útil tiene una definición, límites, método, frecuencia, responsable y controles de calidad claros. También cuenta con una meta o umbral que explica cómo influirá el resultado en la actuación.',
    takeaway: 'Un indicador sin una regla de decisión puede generar datos, pero no valor de gestión.',
  },
  {
    id: 33, domain: 'evidence', difficulty: 'Aplicada',
    question: '¿Por qué el número de árboles plantados no demuestra por sí solo una mejora ecológica?',
    options: ['Los árboles nunca son relevantes', 'Mide una actividad, no la supervivencia, adecuación o función recuperada', 'Los árboles no pueden contarse', 'Una cifra mayor siempre resulta perjudicial'], correct: 1,
    explanation: 'La plantación es un resultado de actividad. El resultado ecológico depende de supervivencia, diversidad, procedencia, estructura, conectividad, estado del suelo y funciones alcanzadas durante un plazo adecuado.',
    takeaway: 'Combina los recuentos de actividad con indicadores de estado y resultado.',
  },
  {
    id: 34, domain: 'evidence', difficulty: 'Aplicada',
    question: '¿Qué debe acompañar a una afirmación ambiental creíble?',
    options: ['Una imagen de naturaleza', 'Alcance, línea base, periodo, método, evidencias y limitaciones', 'Un adjetivo absoluto', 'Una promesa sin criterios medibles'], correct: 1,
    explanation: 'Una afirmación creíble permite comprender qué cambió, respecto a qué, dónde y cuándo. Distingue los resultados medidos de los planes y comunica la incertidumbre y los impactos residuales.',
    takeaway: 'Si la evidencia no puede comprobarse, limita o matiza la afirmación.',
  },
  {
    id: 35, domain: 'evidence', difficulty: 'Avanzada',
    question: 'Si los datos ecológicos están incompletos, ¿qué enfoque es más riguroso?',
    options: ['Ocultar la carencia', 'Documentar la incertidumbre, aplicar precaución proporcionada y mejorar la evidencia', 'Inventar una cifra precisa', 'Detener permanentemente toda evaluación'], correct: 1,
    explanation: 'La falta de datos completos no elimina la necesidad de decidir, pero la incertidumbre debe ser visible. La precaución proporcionada, los supuestos conservadores y un plan específico de mejora reducen el riesgo de una falsa confianza.',
    takeaway: 'La incertidumbre es información que debe gestionarse, no un motivo para fabricar precisión.',
  },
  {
    id: 36, domain: 'evidence', difficulty: 'Aplicada',
    question: '¿Por qué conviene combinar datos de observación de la Tierra y prospecciones de campo?',
    options: ['Los satélites identifican perfectamente todas las especies', 'La cobertura remota y las series temporales pueden validarse e interpretarse localmente', 'El trabajo de campo nunca es necesario', 'Los métodos solo miden valor económico'], correct: 1,
    explanation: 'La observación de la Tierra puede revelar patrones de cobertura, humedad o cambio en áreas extensas y periodos prolongados. Los datos de campo confirman especies, estado y causas que una imagen no siempre permite distinguir de forma fiable.',
    takeaway: 'Utiliza cada método para aquello que puede demostrar y combínalos cuando las evidencias sean complementarias.',
  },
  {
    id: 37, domain: 'evidence', difficulty: 'Avanzada',
    question: '¿Qué combinación permite priorizar mejor un asunto relacionado con la naturaleza?',
    options: ['Atractivo visual e interés mediático', 'Magnitud del impacto, sensibilidad del receptor, dependencia, riesgo y capacidad de influencia', 'Únicamente la medida más barata', 'El número de fotografías disponibles'], correct: 1,
    explanation: 'La priorización debe considerar gravedad y probabilidad de los impactos, sensibilidad e irremplazabilidad ecológica, dependencias y exposición de la organización. También debe diferenciar el control directo de la influencia sobre la cadena de valor.',
    takeaway: 'Prioriza según la importancia y la capacidad de decisión, no únicamente por la visibilidad.',
  },
  {
    id: 38, domain: 'evidence', difficulty: 'Avanzada',
    question: '¿Qué se necesita antes de afirmar que existe «pérdida neta nula»?',
    options: ['Una única actividad de restauración', 'Alcance, métrica, línea base, aplicación de la jerarquía, equivalencia, plazos y balance residual verificado', 'Un presupuesto elevado de comunicación', 'Solo un recuento de hectáreas protegidas'], correct: 1,
    explanation: 'Estas afirmaciones dependen de una contabilidad transparente de pérdidas y ganancias, equivalencia ecológica, adicionalidad, retrasos, fugas y permanencia. También exigen evidencias de que primero se aplicaron prevención y minimización.',
    takeaway: 'Las afirmaciones de balance complejo necesitan evidencias más sólidas que los simples mensajes de actividad.',
  },
  {
    id: 39, domain: 'evidence', difficulty: 'Aplicada',
    question: '¿Por qué los planes de seguimiento deben incluir umbrales y medidas correctoras?',
    options: ['Para alargar los informes', 'Para convertir las observaciones en decisiones de gestión oportunas', 'Para eliminar toda incertidumbre', 'Para evitar asignar responsabilidades'], correct: 1,
    explanation: 'Un umbral identifica cuándo el desempeño sale del rango aceptable, mientras que la medida correctora define qué ocurre a continuación. Sin ambos, el seguimiento puede registrar un deterioro sin cambiar el resultado.',
    takeaway: 'Vincula cada indicador importante con un responsable, un desencadenante y una respuesta.',
  },
  {
    id: 40, domain: 'evidence', difficulty: 'Aplicada',
    question: 'En un sistema de gestión ambiental, ¿qué debe seguir a la identificación de un aspecto significativo?',
    options: ['Únicamente comunicación', 'Controles operativos, responsabilidades, objetivos cuando proceda y evaluación del desempeño', 'Eliminarlo del registro', 'Suponer que el cumplimiento legal es suficiente'], correct: 1,
    explanation: 'Un aspecto significativo debe gestionarse mediante controles y competencia adecuados, apoyados por seguimiento y mejora. La respuesta debe reflejar obligaciones de cumplimiento, riesgos, oportunidades y contexto operativo.',
    takeaway: 'El registro de aspectos es una herramienta de decisión, no el final de un trámite administrativo.',
  },

  {
    id: 41, domain: 'airbus', difficulty: 'Aplicada',
    question: 'Aparece una mancha junto a un drenaje en una zona de mantenimiento del A400M. ¿Qué debe hacerse primero?',
    options: ['Lavarla hacia el drenaje', 'Detener la fuente, contener el vertido y activar el procedimiento de incidente', 'Esperar a que se evapore', 'Cubrirla y continuar los trabajos'], correct: 1,
    explanation: 'La prioridad inmediata es proteger a las personas y evitar que la sustancia alcance el suelo o el agua. Una vez controlada la fuente y contenido el vertido, pueden realizarse la notificación, recuperación, clasificación e investigación.',
    takeaway: 'Controla la fuente y la vía de exposición antes de centrarte en la limpieza o la documentación.',
  },
  {
    id: 42, domain: 'airbus', difficulty: 'Aplicada',
    question: 'Una prueba relacionada con el Eurofighter coincide con una zona y época sensibles para las aves. ¿Cuál es la mejor respuesta inicial?',
    options: ['Continuar sin revisar', 'Evaluar si la ruta, horario o fecha pueden evitar la interacción manteniendo la seguridad', 'Compensar antes de evaluar el impacto', 'Aumentar la frecuencia de las pruebas'], correct: 1,
    explanation: 'La planificación operativa puede eliminar la coincidencia espacial o temporal antes de provocar molestias. Las restricciones de seguridad y misión siguen siendo esenciales, pero deben evaluarse junto a la sensibilidad del receptor y las alternativas viables.',
    takeaway: 'Utiliza la planificación temprana para identificar opciones de prevención antes de depender de medidas conductuales o compensatorias.',
  },
  {
    id: 43, domain: 'airbus', difficulty: 'Aplicada',
    question: 'Al evaluar la ampliación de una instalación industrial, ¿qué alternativa debe analizarse desde el principio?',
    options: ['La que afecta al hábitat más sensible', 'Reutilizar suelo ya desarrollado y reducir la nueva ocupación', 'La opción más visible', 'La opción que exige una mayor huella de iluminación'], correct: 1,
    explanation: 'La reutilización de suelo previamente alterado puede evitar nuevas pérdidas de suelo y hábitat, aunque también deben evaluarse contaminación, seguridad, logística y resiliencia futura. La comparación debe basarse en evidencias y no ser automática.',
    takeaway: 'Una buena evaluación de alternativas analiza ubicación, superficie, diseño y calendario antes de bloquear los impactos.',
  },
  {
    id: 44, domain: 'airbus', difficulty: 'Avanzada',
    question: '¿Cómo puede compatibilizarse la gestión de fauna en un aeródromo con la seguridad aérea?',
    options: ['Atraer fauna a las zonas de movimiento', 'Evaluar conjuntamente el comportamiento de las especies, el hábitat y los peligros operativos', 'Ignorar los movimientos estacionales', 'Eliminar toda la vegetación sin valorar las consecuencias'], correct: 1,
    explanation: 'La seguridad aérea es prioritaria, pero las medidas indiscriminadas pueden crear nuevos atractores o trasladar el riesgo. La gestión debe utilizar evidencias específicas de las especies, diseño del hábitat, seguimiento y coordinación con los equipos operativos.',
    takeaway: 'Gestiona los factores ecológicos que provocan la presencia peligrosa, no solo los animales observados en un momento concreto.',
  },
  {
    id: 45, domain: 'airbus', difficulty: 'Aplicada',
    question: 'En la compra de embalajes de madera, ¿qué evidencia mejora más la diligencia debida relacionada con la naturaleza?',
    options: ['Que el embalaje sea de color verde', 'Origen trazable y gestión forestal responsable verificada de forma independiente', 'Una garantía verbal', 'El precio más bajo sin datos de procedencia'], correct: 1,
    explanation: 'La trazabilidad vincula el producto con el origen del material y permite analizar riesgos de deforestación, legalidad y gestión. La verificación aporta confianza, pero necesita un alcance adecuado y controles de cadena de custodia.',
    takeaway: 'Solicita evidencias que acompañen al material a lo largo de la cadena de suministro, no una promesa genérica del proveedor.',
  },
  {
    id: 46, domain: 'airbus', difficulty: 'Aplicada',
    question: '¿Qué puede mejorar la gestión de la siega en una instalación industrial?',
    options: ['Segar todas las zonas con la misma frecuencia durante todo el año', 'Zonificar la instalación y adaptar el calendario a seguridad, riesgo de incendio y ciclos ecológicos', 'Eliminar el seguimiento', 'Introducir plantas exóticas de rápida expansión'], correct: 1,
    explanation: 'Las distintas áreas desempeñan funciones de seguridad y ecológicas diferentes. Un plan zonificado puede mantener acceso y visibilidad, reducir molestias y permitir una estructura vegetal adecuada donde el riesgo operativo lo permita.',
    takeaway: 'Define la intensidad de gestión según la función y el riesgo en lugar de aplicar un régimen uniforme.',
  },
  {
    id: 47, domain: 'airbus', difficulty: 'Aplicada',
    question: '¿Qué valor aporta la observación de la Tierra a la gestión ambiental?',
    options: ['Siempre sustituye la verificación de campo', 'Ayuda a detectar cambios, comparar periodos y priorizar investigaciones', 'Elimina la necesidad de contexto', 'Solo proporciona imágenes decorativas'], correct: 1,
    explanation: 'Los datos satelitales y aéreos pueden mostrar patrones de cobertura, estado de la vegetación, humedad y cambio a escalas útiles. Su interpretación debe validarse con evidencias locales y una comprensión clara de la resolución y la incertidumbre.',
    takeaway: 'Utiliza los datos remotos para orientar preguntas y trabajo de campo, no para afirmar más de lo que demuestra una imagen.',
  },
  {
    id: 48, domain: 'airbus', difficulty: 'Avanzada',
    question: 'Un cambio de ingeniería introduce un nuevo mineral crítico. ¿Cuál es la respuesta de sostenibilidad más sólida?',
    options: ['Aprobarlo solo por su rendimiento técnico', 'Evaluar rendimiento, trazabilidad, riesgo de abastecimiento, alternativas y compromisos de ciclo de vida', 'Rechazar automáticamente cualquier material nuevo', 'Confiar únicamente en el nombre del proveedor directo'], correct: 1,
    explanation: 'El rendimiento de ingeniería y la aeronavegabilidad siguen siendo esenciales, mientras que la diligencia debida analiza origen, procesado, riesgos ecológicos y sociales, resiliencia de suministro y fin de vida. Las alternativas deben compararse con requisitos coherentes.',
    takeaway: 'Integra la evidencia de abastecimiento al principio del diseño, cuando aún pueden modificarse el material y la arquitectura.',
  },
  {
    id: 49, domain: 'airbus', difficulty: 'Avanzada',
    question: '¿Qué pregunta favorece mejor la circularidad cuando se retira un componente durante un retrofit?',
    options: ['¿Puede desecharse inmediatamente?', '¿Puede inspeccionarse, recertificarse, reutilizarse, remanufacturarse o recuperarse con seguridad?', '¿Puede eliminarse la trazabilidad?', '¿Pueden ignorarse los datos de estado?'], correct: 1,
    explanation: 'Una decisión circular considera estado, seguridad, certificación, trazabilidad, vida remanente y demanda antes de elegir una ruta. La reutilización no es automáticamente preferible si compromete el rendimiento o traslada impactos mayores.',
    takeaway: 'Conserva la información y el valor material respetando las restricciones de aeronavegabilidad y seguridad.',
  },
  {
    id: 50, domain: 'airbus', difficulty: 'Avanzada',
    question: '¿Qué cierra el ciclo de gestión después de un incidente ambiental?',
    options: ['Únicamente la limpieza', 'Análisis de causas, acción correctiva, comprobación de eficacia y aprendizaje compartido', 'Solo un mensaje de comunicación', 'Cerrar el registro inmediatamente'], correct: 1,
    explanation: 'La contención y recuperación resuelven el suceso inmediato. El análisis de causa raíz, las acciones correctivas y la comprobación de eficacia reducen la repetición, mientras que el aprendizaje proporcionado ayuda a otros equipos a controlar la misma vía.',
    takeaway: 'Una acción cerrada no equivale a una acción cuya eficacia se ha demostrado.',
  },
];

const QUESTION_IMAGE_ALTS = [
  '',
  'Bosque templado, pradera y estanque formando un paisaje natural variado.',
  'Lagarto de una isla mediterránea entre rocas y vegetación costera.',
  'Manada de ciervos salvajes atravesando una pradera de montaña.',
  'Planta con flores desconocida junto a una zona europea de transporte.',
  'Castor europeo descansando junto a un río al amanecer.',
  'Líquenes sobre la corteza de un árbol maduro con una observadora al fondo.',
  'Ave, polilla y murciélago distante en el borde de un bosque al anochecer.',
  'Edificio industrial iluminado junto a vegetación oscura durante la noche.',
  'Varias especies silvestres compartiendo una pradera al amanecer.',
  'Carrizal y pradera en primavera con maquinaria inactiva a lo lejos.',
  'Cuenca fluvial que conecta bosque, cultivos y una pequeña población.',
  'Humedal saludable con agua abierta, carrizos y aves acuáticas distantes.',
  'Manchas de bosque conectadas por un seto y un arroyo entre cultivos.',
  'Suelo forestal oscuro con hojarasca, raíces finas y una lombriz.',
  'Paisaje forestal dividido por una carretera.',
  'Pradera intacta junto a una instalación industrial distante.',
  'Instalación industrial dentro de una amplia cuenca fluvial y campos agrícolas.',
  'Nave de fabricación aeronáutica abierta hacia el paisaje circundante.',
  'Arroyo con vegetación integrado junto a edificios empresariales modernos.',
  'Bosque costero maduro bajo un tiempo cambiante.',
  'Equipo de proyecto reunido alrededor de una maqueta sin marcas.',
  'Límite de una obra tranquila junto al borde de un bosque intacto.',
  'Perímetro aeronáutico seguro e iluminado junto a vegetación oscura.',
  'Obra de restauración de una ribera degradada con maquinaria inactiva.',
  'Obra de infraestructura con una nueva zona de hábitat en la distancia.',
  'Estanque joven y poco profundo con otro más antiguo al fondo.',
  'Planta con flores desconocida observada en una instalación industrial.',
  'Equipo de campo recorriendo una pradera restaurada durante una visita.',
  'Mezcla natural de hierbas y flores silvestres en una pradera restaurada.',
  'Motor de aeronave retirado sobre un banco limpio de mantenimiento.',
  'Estanque forestal tranquilo rodeado de vegetación madura.',
  'Especialista ambiental en campo con tableta y maletín de sensores cerrado.',
  'Filas de árboles jóvenes recién plantados en un campo abierto.',
  'Ponente corporativo hablando junto a una pantalla vacía.',
  'Ecóloga de campo observando un paisaje parcialmente cubierto por la niebla.',
  'Especialista ambiental en terreno remoto bajo una pequeña aeronave de observación.',
  'Pradera natural y arroyo junto a una instalación industrial aeronáutica.',
  'Pequeño equipo visitando un hábitat natural restaurado recientemente.',
  'Estación compacta de sensores ambientales junto a un estanque tranquilo.',
  'Equipo de gestión ambiental reunido junto a una pizarra sin marcas.',
  'A400M en un hangar de mantenimiento con un desagüe y una pequeña mancha.',
  'Eurofighter junto a una pradera de aeródromo en primavera con aves distantes.',
  'Instalación aeronáutica con un solar desarrollado vacío y un campo natural.',
  'Pista de aeródromo, aves distantes y vehículo de gestión de fauna estacionado.',
  'Cajas de transporte de madera dentro de un almacén logístico aeronáutico.',
  'Pradera de un campus industrial con distintas alturas y una segadora parada.',
  'Analista observando una imagen satelital del paisaje en una sala de operaciones.',
  'Muestras de minerales críticos junto a un módulo electrónico aeronáutico.',
  'Componente de aviónica retirado sobre un banco de mantenimiento de retrofit.',
  'Equipo de mantenimiento aeronáutico reunido después de un incidente.',
];

QUESTIONS.forEach((question) => {
  question.image = `./assets/questions/q${String(question.id).padStart(2, '0')}.webp`;
  question.imageAlt = QUESTION_IMAGE_ALTS[question.id];
});

window.KNOWLEDGE_CHECK = { DOMAINS, QUESTIONS };
